# ★第一部分，系统配置
mixed-port: 7891
redir-port: 17891
allow-lan: true
bind-address: '*'
mode: rule
log-level: silent
ipv6: false
#external-controller: 0.0.0.0:9090
#external-ui: dashboardB
#interface-name: en0

# ★第二部分，DNS配置
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - 'localhost.ptlogin2.qq.com'
    - 'dns.msftncsi.com'
    - 'www.msftncsi.com'
    - 'www.msftconnecttest.com'
  nameserver:
    - 223.5.5.5
    - 119.29.29.29

# ★第三部分，代理配置



proxy-groups:
  - name: "REALFISH"
    type: select
    proxies:
      - home200_37890
      - home200_7890
      - REJECT
      - DIRECT
  - name: "Just4FaceBook"
    type: select
    proxies:
      - home200_37890
      - DIRECT
      - quest_3
      - quest_2
      - S_3
      - S_2
      - V_3
      - V_2
      - home100_57890
      - home200_57890
      - home100_7890
      - home200_7890
      - home100_64890
      - home200_64890
      - home200_9909
      
  - name: "FuckWall"
    type: select
    proxies:
      - home200_37890
      - quest_3
      - quest_2
      - S_3
      - S_2
      - V_3
      - V_2
      - home100_57890
      - home200_57890
      - home100_7890
      - home200_7890
      - home100_64890
      - home200_64890
      - home200_9909
      - DIRECT
      
  - name: "quest_3"
    type: select
    use:
      - config003Pool_Quest 
 
  - name: "quest_2"
    type: select
    use:
      - config002Pool_Quest  

  - name: "S_3"
    type: select
    use:
      - config003Pool_S
      
  - name: "V_3"
    type: select
    use:
      - config003Pool_V

  - name: "S_2"
    type: select
    use:
      - config002Pool_S 
      
  - name: "V_2"
    type: select
    use:
      - config002Pool_V 

  - name: "Final-------------------------------------------"
    type: select
    proxies:
      - FuckWall
      - DIRECT
proxies:
  - name: home200_57890
    type: socks5
    server: 192.168.50.200
    port: 57890
    udp: true
  - name: home100_57890
    type: socks5
    server: 192.168.50.200
    port: 57890
    udp: true
  - name: home100_7890
    type: socks5
    server: 192.168.50.100
    port: 7890
    udp: true
  - name: home200_7890
    type: socks5
    server: 192.168.50.200
    port: 7890
    udp: true
  - name: home100_64890
    type: socks5
    server: 192.168.50.100
    port: 64890
    udp: true
  - name: home200_64890
    type: socks5
    server: 192.168.50.200
    port: 64890
    udp: true
  - name: home200_9909
    type: socks5
    server: 192.168.50.200
    port: 9909
    udp: true
  - name: home200_37890
    type: socks5
    server: 192.168.50.200
    port: 37890
    udp: true

proxy-providers:
  "config003Pool_Quest":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/config003@main/config_quest.yaml"
    url: "https://raw.fastgit.org/misersun/config003/main/config_quest.yaml"
    interval: 3600
    path: ./download/tested_config003_quest.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config002Pool_Quest":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/config002@main/config_quest.yaml"
    url: "https://raw.fastgit.org/misersun/config002/main/config_quest.yaml"
    interval: 3600
    path: ./download/tested_config002_quest.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config003Pool_V":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/config003@main/config_v.yaml"
    url: "https://raw.fastgit.org/misersun/config003/main/config_v.yaml"
    interval: 3600
    path: ./download/tested_config003_v.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config002Pool_V":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/config002@main/config_v.yaml"
    url: "https://raw.fastgit.org/misersun/config002/main/config_v.yaml"
    interval: 3600
    path: ./download/tested_config002_v.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config003Pool_S":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/config003@main/config_s.yaml"
    url: "https://raw.fastgit.org/misersun/config003/main/config_s.yaml"
    interval: 3600
    path: ./download/tested_config003_s.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config002Pool_S":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/config002@main/config_s.yaml"
    url: "https://raw.fastgit.org/misersun/config002/main/config_s.yaml"
    interval: 3600
    path: ./download/tested_config002_s.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

# ★第四部分，规则配置
rule-providers:
  # reject:
    # type: http
    # behavior: domain
    # #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    # url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/reject.txt"
    # path: ./ruleset/reject.yaml
    # interval: 86400

  icloud:
    type: http
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    #url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

rules:
  #- IP-CIDR,52.53.43.176/32,REJECT,no-resolve
  #- SRC-IP-CIDR,52.53.43.176/32,REJECT,no-resolve
  - IP-CIDR,52.53.43.176/32,REALFISH,no-resolve
  #- DOMAIN,message.rvrfserver.com,REJECT
  #- DOMAIN,static.xx.fbcdn.net,REJECT
  #- DOMAIN,steamcdn-a.akamaihd.net,REJECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN-SUFFIX,googleapis.cn,FuckWall
  - DOMAIN-KEYWORD,facebook,Just4FaceBook
  - DOMAIN-KEYWORD,oculus,Just4FaceBook
  - DOMAIN-KEYWORD,oculuscdn,Just4FaceBook
  - DOMAIN-KEYWORD,oculuscdn,Just4FaceBook
  - DOMAIN-SUFFIX,meta.com,Just4FaceBook
  - RULE-SET,private,DIRECT
  #- RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,direct,DIRECT  
  - RULE-SET,tld-not-cn,FuckWall
  - RULE-SET,gfw,FuckWall
  - RULE-SET,greatfire,FuckWall
  - RULE-SET,google,FuckWall
  - RULE-SET,proxy,FuckWall
  - RULE-SET,telegramcidr,FuckWall
  - GEOIP,CN,DIRECT
#  - MATCH,FuckWall
  - MATCH,Final-------------------------------------------