# ★第一部分，系统配置
mixed-port: 7891
redir-port: 17891
allow-lan: true
bind-address: '*'
mode: rule
log-level: silent
ipv6: false
#external-controller: 0.0.0.0:9090
#external-ui: dashboardB
#interface-name: en0

# ★第二部分，DNS配置
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - 'localhost.ptlogin2.qq.com'
    - 'dns.msftncsi.com'
    - 'www.msftncsi.com'
    - 'www.msftconnecttest.com'
  nameserver:
    - 223.5.5.5
    - 119.29.29.29

# ★第三部分，代理配置

proxy-groups:
  - name: "SSR_GAME"
    type: select
    use:
      - ssr_game   

proxy-providers:
  "ssr_game":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config003@main/config_ssr_game.yaml"
    #url: "https://raw.fastgit.org/misersun/config003/main/config_ssr_game.yaml"
    interval: 3600
    path: ./download/config_ssr_game.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
