# ★第一部分，系统配置
mixed-port: 7891
redir-port: 17891
allow-lan: true
bind-address: '*'
mode: rule
log-level: silent
ipv6: false
#external-controller: 0.0.0.0:9090
#external-ui: dashboardB
#interface-name: en0

# ★第二部分，DNS配置
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - 'localhost.ptlogin2.qq.com'
    - 'dns.msftncsi.com'
    - 'www.msftncsi.com'
    - 'www.msftconnecttest.com'
  nameserver:
    - 223.5.5.5
    - 119.29.29.29

# ★第三部分，代理配置



proxy-groups:
  - name: "FuckWall"
    type: select
    proxies:
      - load-balance-S-config003
      - load-balance-S-config002
      - load-balance-S-config001
      - load-balance-V-config003
      - load-balance-V-config002      
      - load-balance-V-config001
      - load-balance-config003
      - load-balance-config002
      - load-balance-config001           
      - MySelected_S_config003
      - MySelected_V_config003
      - MySelected_config003
      - MySelected_S_config002
      - MySelected_V_config002
      - MySelected_S_config001
      - MySelected_V_config001 
      - tested_config003_pool      
      - tested_config002_pool
      - tested_config001_pool
      - home_socks5
      - home_socks6
      - DIRECT
       
  - name: "MySelected_S_config003"
    type: select
    use:
      - config003Pool_S
      
  - name: "MySelected_V_config003"
    type: select
    use:
      - config003Pool_V
      
  - name: "MySelected_config003"
    type: select
    use:
      - config003Pool 

  - name: "MySelected_S_config002"
    type: select
    use:
      - config002Pool_S 
      
  - name: "MySelected_V_config002"
    type: select
    use:
      - config002Pool_V  

  - name: "MySelected_S_config001"
    type: select
    use:
      - config001Pool_S      

  - name: "MySelected_V_config001"
    type: select
    use:
      - config001Pool_V 

  - name: "Just4FaceBook"
    type: select
    proxies:
      - DIRECT
      - Just4FaceBook_3_MySelected
      - Just4FaceBook_2_MySelected
      
  - name: "Just4FaceBook_3_MySelected"
    type: select
    use:
      - US003_Pool

  - name: "Just4FaceBook_2_MySelected"
    type: select
    use:
      - US002_Pool

  - name: "Final-------------------------------------------"
    type: select
    proxies:
      - FuckWall
      - DIRECT

  - name: "load-balance-config001"
    type: load-balance
    use:
      - config001Pool
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing
 
  - name: "load-balance-config003"
    type: load-balance
    use:
      - config003Pool
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing 
 
  - name: "load-balance-config002"
    type: load-balance
    use:
      - config002Pool
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing
 
  - name: "load-balance-V-config001"
    type: load-balance
    use:
      - config001Pool_V
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing
 
  - name: "load-balance-V-config003"
    type: load-balance
    use:
      - config003Pool_V
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing 
 
  - name: "load-balance-V-config002"
    type: load-balance
    use:
      - config002Pool_V
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing

  - name: "load-balance-S-config001"
    type: load-balance
    use:
      - config001Pool_S
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing
 
  - name: "load-balance-S-config003"
    type: load-balance
    use:
      - config003Pool_S
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing 
 
  - name: "load-balance-S-config002"
    type: load-balance
    use:
      - config002Pool_S
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing

  - name: "tested_config001_pool"
    type: url-test
    use:
      - config001Pool
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50
 
  - name: "tested_config003_pool"
    type: url-test
    use:
      - config003Pool
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50

  - name: "tested_config002_pool"
    type: url-test
    use:
      - config002Pool
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50
 
proxies:
  - name: home_socks5
    type: socks5
    server: 192.168.50.200
    port: 57890
  - name: home_socks6
    type: socks5
    server: 192.168.50.200
    port: 64891
    
proxy-providers:
  "config001Pool":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config001@main/config_other.yaml"
    #url: "https://raw.fastgit.org/misersun/config001/main/config_other.yaml"

    interval: 3600
    path: ./download/tested_config001.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config003Pool":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config003@main/config_other.yaml"
    #url: "https://raw.fastgit.org/misersun/config003/main/config_other.yaml"
    interval: 3600
    path: ./download/tested_config003.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config002Pool":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config002@main/config_other.yaml"
    #url: "https://raw.fastgit.org/misersun/config002/main/config_other.yaml"
    interval: 3600
    path: ./download/tested_config002.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config001Pool_V":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config001@main/config_v.yaml"
    #url: "https://raw.fastgit.org/misersun/config001/main/config_v.yaml"
    interval: 3600
    path: ./download/tested_config001_v.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config003Pool_V":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config003@main/config_v.yaml"
    #url: "https://raw.fastgit.org/misersun/config003/main/config_v.yaml"
    interval: 3600
    path: ./download/tested_config003_v.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config002Pool_V":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config002@main/config_v.yaml"
    #url: "https://raw.fastgit.org/misersun/config002/main/config_v.yaml"
    interval: 3600
    path: ./download/tested_config002_v.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config001Pool_S":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config001@main/config_s.yaml"
    #url: "https://raw.fastgit.org/misersun/config001/main/config_s.yaml"
    interval: 3600
    path: ./download/tested_config001_s.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config003Pool_S":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config003@main/config_s.yaml"
    #url: "https://raw.fastgit.org/misersun/config003/main/config_s.yaml"
    interval: 3600
    path: ./download/tested_config003_s.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config002Pool_S":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config002@main/config_s.yaml"
    #url: "https://raw.fastgit.org/misersun/config002/main/config_s.yaml"
    interval: 3600
    path: ./download/tested_config002_s.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config002Pool_ALL":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config002@main/config_all.yaml"
    #url: "https://raw.fastgit.org/misersun/config002/main/config_all.yaml"
    interval: 3600
    path: ./download/tested_config002_all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "US002_Pool":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config002@main/config_us.yaml"
    #url: "https://raw.fastgit.org/misersun/config002/main/config_us.yaml"
    interval: 3600
    path: ./download/US002.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "US003_Pool":
    type: http
    url: "https://cdn.jsdelivr.net/gh/misersun/config003@main/config_us.yaml"
    #url: "https://raw.fastgit.org/misersun/config003/main/config_us.yaml"
    interval: 3600
    path: ./download/US003.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
      

# ★第四部分，规则配置
rule-providers:
  # reject:
    # type: http
    # behavior: domain
    # url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    # #url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/reject.txt"
    # path: ./ruleset/reject.yaml
    # interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    #url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    #url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    #url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    #url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    #url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    #url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    #url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    #url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    #url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    #url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    #url: "https://raw.fastgit.org/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

rules:
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN-SUFFIX,googleapis.cn,FuckWall
  - DOMAIN-KEYWORD,facebook,Just4FaceBook
  - DOMAIN-KEYWORD,oculus,Just4FaceBook
  - DOMAIN-KEYWORD,oculuscdn,Just4FaceBook
  - DOMAIN-SUFFIX,myip.com,Just4FaceBook
  #- RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,FuckWall
  - RULE-SET,proxy,FuckWall
  - RULE-SET,direct,DIRECT
  - RULE-SET,telegramcidr,FuckWall
  - GEOIP,CN,DIRECT
#  - MATCH,FuckWall
  - MATCH,Final-------------------------------------------