socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: silent

dns:
  enable: false

proxies:
  - {name: 🇷🇺 Relay_馃嚭馃嚫US-馃嚪馃嚭RU_2443 |22.73Mb, server: 172.67.150.130, port: 80, type: vmess, uuid: 3d31728e-064d-42b8-b945-f79c008f73fc, alterId: 233, cipher: auto, tls: false, network: ws, ws-path: /, ws-headers: {Host: free-russian01-cdn.xiaohouzi.club}}
  - {name: 馃嚞馃嚙 GB_32, server: 35.178.68.152, port: 47611, type: vmess, uuid: 97a4d167-b361-48b8-b004-8bc45669e334, alterId: 0, cipher: auto, tls: false}
  - {name: 🇯🇵 馃嚡馃嚨JP_3662, server: auto.freev2.top, port: 15482, type: vmess, uuid: 354e4f20-7a3b-4ee1-b6a7-3c34d1eb1da9, alterId: 1, cipher: auto, tls: false}

#free
  - {name: https://git.io/v9999 clash only, server: 45.76.76.213, port: 11383, type: vmess, uuid: aed7a819-7134-4d6d-b870-238fad1cd994, alterId: 0, cipher: auto, tls: false, network: ws, ws-path: /, ws-headers: {Host: 45.76.76.213}}
  - {name: https://git.io/v9999 clash ip3 87, server: 54.238.21.12, port: 2222, type: vmess, uuid: 57b9f56f-8f51-3af3-87de-87b6e46b2e17, alterId: 0, cipher: auto, tls: false, network: ws, ws-path: /, ws-headers: {Host: 54.238.21.12}}
  - {name: https://git.io/v9999 clash ip1, server: 82.102.26.117, port: 44236, type: ss, cipher: aes-256-gcm, password: FWrXcxPZjJxAN89xLgqY3Acp}
  - {name: https://git.io/v9999 clash ip1 8, server: 66.55.148.42, port: 810, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: https://git.io/v9999 clash ip1 16, server: 51.89.99.59, port: 800, type: ss, cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao}
  - {name: https://git.io/v9999 clash ip1 34, server: 138.199.9.202, port: 31944, type: ss, cipher: aes-256-gcm, password: aYNeKDMzYQYw4KbUbJA8Wszq}
  - {name: https://git.io/v9999 clash ip1 6, server: 85.10.50.164, port: 50168, type: ss, cipher: aes-256-gcm, password: WCuz7yrfZSCQQXSNrtGPz2HT}
  - {name: bbbbbbbbb, server: 211.23.132.124, port: 9233, type: vmess, uuid: be58f4e4-894a-47ee-8836-cf75e74fa9c9, alterId: 64, cipher: auto, tls: false, network: ws, ws-path: /, ws-headers: {Host: 211.23.132.124}}
  - {name: https://git.io/v9999 clash ip3 54, server: 13.70.28.145, port: 34323, type: vmess, uuid: 5a2056b9-61c5-4737-b153-b2775ec8bad9, alterId: 64, cipher: auto, tls: false}
  - {name: https://git.io/v9999 clash ip3 86, server: 146.59.13.37, port: 80, type: vmess, uuid: b79212e2-b670-4d4b-8c22-eb796921b97a, alterId: 64, cipher: auto, tls: false, network: ws, ws-path: /sshocean, ws-headers: {Host: 146.59.13.37}}
  - {name: https://git.io/v9999 clash ip1 56, server: 104.200.131.165, port: 50168, type: ss, cipher: aes-256-gcm, password: WCuz7yrfZSCQQXSNrtGPz2HT}
  - {name: https://git.io/v9999 clash ip1 27, server: 66.115.175.37, port: 50168, type: ss, cipher: aes-256-gcm, password: WCuz7yrfZSCQQXSNrtGPz2HT}
  - {name: https://git.io/v9999 clash ip1 11, server: 185.44.76.188, port: 50168, type: ss, cipher: aes-256-gcm, password: WCuz7yrfZSCQQXSNrtGPz2HT}
  - {name: https://git.io/v9999 clash ip1 19, server: 195.47.194.42, port: 34815, type: ss, cipher: aes-256-gcm, password: LkFAzkzXkSCRYa2CsRdL8cGb}
  - {name: https://git.io/v9999 clash ip1 44, server: 91.90.123.115, port: 38620, type: ss, cipher: aes-256-gcm, password: Kquv5UhvZXNMemAQy8DxZ7qn}
  - {name: https://git.io/v9999 clash ip1 13, server: 198.147.22.87, port: 50168, type: ss, cipher: aes-256-gcm, password: WCuz7yrfZSCQQXSNrtGPz2HT}
  - {name: https://git.io/v9999 clash ip1 23, server: 198.147.22.87, port: 31572, type: ss, cipher: aes-256-gcm, password: n8w4StnbVD9dmXYn4Ajt87EA}
  - {name: https://git.io/v9999 clash ip1 25, server: 195.47.194.42, port: 33992, type: ss, cipher: aes-256-gcm, password: 8n6pwAcrrv2pj6tFY2p3TbQ6}
  - {name: https://git.io/v9999 clash ip1 33, server: 195.47.194.42, port: 35294, type: ss, cipher: aes-256-gcm, password: J9Y2ncrdPEC38gwydNFFGBna}
  - {name: https://git.io/v9999 clash ip1 42, server: 91.90.123.115, port: 48938, type: ss, cipher: aes-256-gcm, password: 4ejJ8n5ddLuYDUHGXJre2ufJ}
  - {name: https://git.io/v9999 clash ip1 46, server: 91.90.123.115, port: 33148, type: ss, cipher: aes-256-gcm, password: CMduaFXddcQbwNAAs7xFDnc8}
  - {name: https://git.io/v9999 clash ip1 26, server: 195.47.194.42, port: 37588, type: ss, cipher: aes-256-gcm, password: kD9vkjnE6dsUzwQfvKkPkQAd}
  - {name: https://git.io/v9999 clash ip1 28, server: 198.147.22.87, port: 33998, type: ss, cipher: aes-256-gcm, password: NHwQTPLCfaTMSqTnU3mjcSxe}
  - {name: https://git.io/v9999 clash ip1 29, server: 198.147.22.87, port: 32558, type: ss, cipher: aes-256-gcm, password: gJYzm3TLbdL495ryQptaJXQk}
  - {name: https://git.io/v9999 clash ip1 31, server: 195.47.194.42, port: 31944, type: ss, cipher: aes-256-gcm, password: aYNeKDMzYQYw4KbUbJA8Wszq}
  - {name: https://git.io/v9999 clash ip1 40, server: 85.10.50.164, port: 37588, type: ss, cipher: aes-256-gcm, password: kD9vkjnE6dsUzwQfvKkPkQAd}
  - {name: https://git.io/v9999 clash ip1 43, server: 91.90.123.115, port: 47121, type: ss, cipher: aes-256-gcm, password: CTK8GXFQgKYQErrghPJfZ6tk}
  - {name: https://git.io/v9999 clash ip1 45, server: 91.90.123.115, port: 37588, type: ss, cipher: aes-256-gcm, password: kD9vkjnE6dsUzwQfvKkPkQAd}
  - {name: https://git.io/v9999 clash ip1 2, server: 91.90.123.115, port: 47027, type: ss, cipher: aes-256-gcm, password: Vt5pBJFwdtNB26cJbTXxm88Z}
  - {name: https://git.io/v9999 clash ip1 3, server: 91.90.123.115, port: 40093, type: ss, cipher: aes-256-gcm, password: x23Z4LGkGDkThZ9Kaz4DURQp}
  - {name: https://git.io/v9999 clash ip1 12, server: 198.8.92.84, port: 49396, type: ss, cipher: aes-256-gcm, password: BdRWC38L5JUDMTYNNxJGcUwB}
  - {name: https://git.io/v9999 clash ip1 21, server: 198.147.22.87, port: 33992, type: ss, cipher: aes-256-gcm, password: 8n6pwAcrrv2pj6tFY2p3TbQ6}
  - {name: https://git.io/v9999 clash ip1 35, server: 198.8.92.84, port: 35294, type: ss, cipher: aes-256-gcm, password: J9Y2ncrdPEC38gwydNFFGBna}
  - {name: https://git.io/v9999 clash ip1 41, server: 91.90.123.115, port: 49339, type: ss, cipher: aes-256-gcm, password: suucSeVLmt6PQKAP77NtGw9x}
  - {name: https://git.io/v9999 clash ip1 47, server: 198.8.92.84, port: 44945, type: ss, cipher: aes-256-gcm, password: F5bKkb9ggkLx4JbQrbLn7LjZ}
  - {name: https://git.io/v9999 clash ip1 49, server: 91.90.123.115, port: 49126, type: ss, cipher: aes-256-gcm, password: wrCaGtrUbzeRqQLdc8Kmk3Nd}
  - {name: https://git.io/v9999 clash ip1 55, server: 91.90.123.115, port: 31572, type: ss, cipher: aes-256-gcm, password: n8w4StnbVD9dmXYn4Ajt87EA}
  - {name: https://git.io/v9999 clash ip1 64, server: 198.8.92.84, port: 40093, type: ss, cipher: aes-256-gcm, password: x23Z4LGkGDkThZ9Kaz4DURQp}
  - {name: https://git.io/v9999 clash ip1 69, server: 198.8.92.84, port: 37588, type: ss, cipher: aes-256-gcm, password: kD9vkjnE6dsUzwQfvKkPkQAd}
  - {name: https://git.io/v9999 clash ip1 70, server: 198.8.92.84, port: 50168, type: ss, cipher: aes-256-gcm, password: WCuz7yrfZSCQQXSNrtGPz2HT}

proxy-groups:
  - name: "testGithub"
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

rules:
  - MATCH,testGithub
