# ★第一部分，系统配置
mixed-port: 7891
redir-port: 17891
allow-lan: true
bind-address: '*'
mode: rule
log-level: silent
ipv6: false
#external-controller: 0.0.0.0:9090
#external-ui: dashboardB
#interface-name: en0

# ★第二部分，DNS配置
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - 'localhost.ptlogin2.qq.com'
    - 'dns.msftncsi.com'
    - 'www.msftncsi.com'
    - 'www.msftconnecttest.com'
  nameserver:
    - 223.5.5.5
    - 119.29.29.29

# ★第三部分，代理配置



proxy-groups:
  - name: "FuckWall"
    type: select
    proxies:
      - load-balance-mypool
      - load-balance-free
      - load-balance-V-config001
      - load-balance-V-config003
      - load-balance-V-config002
      - load-balance-config001
      - load-balance-config003
      - load-balance-config002
      - load-balance-other
      - MySelected1
      - MySelected2
      - MySelected_config003
      - MySelected_V_config003
      - MySelected_V_config001
      - MySelected_V_config002
      - tested_BaDu
      - tested_freenodes
      - tested_freebaipiao
      - tested_config003_pool
      - tested_config001_pool
      - tested_config002_pool
      - tested_mypool
      - tested_lonxin
      - tested-free-2
      - tested-free-4
      - tested-free-6
      - DIRECT
 
  - name: "MySelected1"
    type: select
    use:
      - free_2
      - free_4
      - free_6
      - lonxin_all

  - name: "MySelected2"
    type: select
    use:
      - config002Pool
      - config001Pool      
      - MyPool
      - BaDu_all
      - freenodes_all
      - freebaipiao_all

  - name: "MySelected_V_config003"
    type: select
    use:
      - config003Pool_V
      
  - name: "MySelected_config003"
    type: select
    use:
      - config003Pool 

  - name: "MySelected_V_config001"
    type: select
    use:
      - config001Pool_V   

  - name: "MySelected_V_config002"
    type: select
    use:
      - config002Pool_V  
     

  - name: "Just4FaceBook"
    type: select
    proxies:
      - DIRECT
      - Just4FaceBook_MySelected


  - name: "Just4FaceBook_MySelected"
    type: select
    use:
      - config003Pool
      - config001Pool
      - config002Pool
      - MyPool
      - free_2
      - free_4
      - free_6
      - BaDu_all
      - freenodes_all
      - freebaipiao_all
      - lonxin_all

  - name: "Final-------------------------------------------"
    type: select
    proxies:
      - FuckWall
      - DIRECT

  - name: "load-balance-free"
    type: load-balance
    use:
      - free_2
      - free_4
      - free_6
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing
      
  - name: "load-balance-mypool"
    type: load-balance
    use:
      - MyPool
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing
 
  - name: "load-balance-config001"
    type: load-balance
    use:
      - config001Pool
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing
 
  - name: "load-balance-config003"
    type: load-balance
    use:
      - config003Pool
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing 
 
  - name: "load-balance-config002"
    type: load-balance
    use:
      - config002Pool
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing
 
  - name: "load-balance-V-config001"
    type: load-balance
    use:
      - config001Pool_V
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing
 
  - name: "load-balance-V-config003"
    type: load-balance
    use:
      - config003Pool_V
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing 
 
  - name: "load-balance-V-config002"
    type: load-balance
    use:
      - config002Pool_V
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing
  
  - name: "load-balance-other"
    type: load-balance
    use:
      - BaDu_all
      - freenodes_all
      - freebaipiao_all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing

  - name: "tested_config001_pool"
    type: url-test
    use:
      - config001Pool
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50
 
  - name: "tested_config003_pool"
    type: url-test
    use:
      - config003Pool
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50

  - name: "tested_config002_pool"
    type: url-test
    use:
      - config002Pool
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50
  
  - name: "tested_mypool"
    type: url-test
    use:
      - MyPool
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50
 
  - name: "tested_BaDu"
    type: url-test
    use:
      - BaDu_all
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50

  - name: "tested_freenodes"
    type: url-test
    use:
      - freenodes_all
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50

  - name: "tested_freebaipiao"
    type: url-test
    use:
      - freebaipiao_all
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50

  - name: "tested_lonxin"
    type: url-test
    use:
      - lonxin_all
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50
 
  # - name: "tested-free-1"
    # type: url-test
    # use:
      # - free_1
    # url: 'http://www.gstatic.com/generate_204'
    # interval: 600
    # tolerance: 50

  - name: "tested-free-2"
    type: url-test
    use:
      - free_2
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50

  # - name: "tested-free-3"
    # type: url-test
    # use:
      # - free_3
    # url: 'http://www.gstatic.com/generate_204'
    # interval: 600
    # tolerance: 50

  - name: "tested-free-4"
    type: url-test
    use:
      - free_4
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50

  # - name: "tested-free-5"
    # type: url-test
    # use:
      # - free_5
    # url: 'http://www.gstatic.com/generate_204'
    # interval: 600
    # tolerance: 50

  - name: "tested-free-6"
    type: url-test
    use:
      - free_6
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    tolerance: 50

 
proxy-providers:
  "config001Pool":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/config001@main/config_other.yaml"
    url: "https://raw.fastgit.org/misersun/config001/main/config_other.yaml"

    interval: 3600
    path: ./download/tested_config001.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config003Pool":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/config003@main/config_other.yaml"
    url: "https://raw.fastgit.org/misersun/config003/main/config_other.yaml"
    interval: 3600
    path: ./download/tested_config003.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config002Pool":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/config002@main/config_other.yaml"
    url: "https://raw.fastgit.org/misersun/config002/main/config_other.yaml"
    interval: 3600
    path: ./download/tested_config002.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config001Pool_V":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/config001@main/config_v.yaml"
    url: "https://raw.fastgit.org/misersun/config001/main/config_v.yaml"
    interval: 3600
    path: ./download/tested_config001_v.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config003Pool_V":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/config003@main/config_v.yaml"
    url: "https://raw.fastgit.org/misersun/config003/main/config_v.yaml"
    interval: 3600
    path: ./download/tested_config003_v.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "config002Pool_V":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/config002@main/config_v.yaml"
    url: "https://raw.fastgit.org/misersun/config002/main/config_v.yaml"
    interval: 3600
    path: ./download/tested_config002_v.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  "MyPool":
    type: http
    #url: "https://cdn.jsdelivr.net/gh/misersun/XXX@main/my.yaml"
    url: "https://raw.fastgit.org/misersun/XXX/main/my.yaml"
    interval: 3600
    path: ./download/my.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  free_2:
    type: http
    url: "https://cdn.jsdelivr.net/gh/Alvin9999/pac2@latest/clash/config.yaml"     
    path: ./download/free-2.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  # free_3:
    # type: http
    # url: "https://gitlab.com/free9999/ipupdate/-/raw/master/clash/2/config.yaml"     
    # path: ./download/free-3.yaml
    # health-check:
      # enable: true
      # interval: 600
      # url: http://www.gstatic.com/generate_204

  free_4:
    type: http
    url: "https://cdn.jsdelivr.net/gh/Alvin9999/pac2@latest/clash/2/config.yaml"     
    path: ./download/free-4.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  # free_5:
    # type: http
    # url: "https://gitlab.com/free9999/ipupdate/-/raw/master/clash/3/config.yaml"     
    # path: ./download/free-5.yaml
    # health-check:
      # enable: true
      # interval: 600
      # url: http://www.gstatic.com/generate_204

  free_6:
    type: http
    url: "https://cdn.jsdelivr.net/gh/Alvin9999/pac2@latest/clash/3/config.yaml"     
    path: ./download/free-6.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204


  lonxin_all:
    type: http
    url: "https://fq.lonxin.net/clash/proxies"
    path: ./download/lonxin_all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204


#八度科技
  BaDu_all:
    type: http
    url: "https://cdn.jsdelivr.net/gh/chfchf0306/clash@main/clash"
    #url: "https://raw.fastgit.org/chfchf0306/clash/main/clash"     
    path: ./download/BaDu_all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

#https://github.com/zyzmzyz/free-nodes
  freenodes_all:
    type: http
    url: "https://cdn.jsdelivr.net/gh/zyzmzyz/free-nodes@master/Clash.yml"     
    path: ./download/freenodes_all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204


#https://raw.githubusercontent.com/freebaipiao/freebaipiao/main/GfwserveClash.yaml
  freebaipiao_all:
    type: http
    url: "https://cdn.jsdelivr.net/gh/freebaipiao/freebaipiao@main/GfwserveClash.yaml"
    #url: "https://raw.fastgit.org/freebaipiao/freebaipiao/main/GfwserveClash.yaml"     
    path: ./download/freebaipiao_all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

# ★第四部分，规则配置
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

rules:
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN-SUFFIX,googleapis.cn,FuckWall
  - DOMAIN-KEYWORD,facebook,Just4FaceBook
  - DOMAIN-KEYWORD,oculus,Just4FaceBook
  - DOMAIN-KEYWORD,oculuscdn,Just4FaceBook
  - DOMAIN-SUFFIX,myip.com,Just4FaceBook
  #- RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,FuckWall
  - RULE-SET,proxy,FuckWall
  - RULE-SET,direct,DIRECT
  - RULE-SET,telegramcidr,FuckWall
  - GEOIP,CN,DIRECT
#  - MATCH,FuckWall
  - MATCH,Final-------------------------------------------
